name = "PathFollowing"
uuid = "a5fbd3e6-a7c5-4efb-a1cb-e5ea7d274979"
authors = ["Olivier Cots <olivier.cots@enseeiht.fr>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.8"